export const routes = {
  home: "/",
  tournaments: "/tournaments",
  tournamentDetails: "/tournaments/:id",
  clubs: "/clubs",
  clubDetails: "/clubs/:clubId",
  clubTournaments: "/clubs/:clubId/tournaments",
  clubGames: "/clubs/:clubId/games",
  clubLeaderboards: "/clubs/:clubId/leaderboards",
  games: "/games",
  gameCategory: "/games/categories/:categoryId",
  gameDetails: "/games/:gameId",
  leaderboards: "/leaderboards",
  players: "/players",
  playerProfile: "/players/:playerId",
  login: "/login",
  register: "/register",
  clubRegister: "/register/club",
  myEvents: "/me/events",
  myProfile: "/me/profile",
  myStats: "/me/stats",
  myHistory: "/me/history",
  notifications: "/me/notifications",
  clubAdminDashboard: "/club-admin/:clubId",
  clubAdminTournaments: "/club-admin/:clubId/tournaments",
  clubAdminTournamentBuilder: "/club-admin/:clubId/tournaments/new",
  clubAdminEditTournament: "/club-admin/:clubId/tournaments/:id/edit",
  clubAdminTournamentRegistrations:
    "/club-admin/:clubId/tournaments/:id/registrations",
  clubAdminGameInventory: "/club-admin/:clubId/games",
  clubAdminStaff: "/club-admin/:clubId/staff",
  clubAdminProfileEdit: "/club-admin/:clubId/profile/edit",
  appAdminDashboard: "/admin",
  appAdminClubRequests: "/admin/club-requests",
  appAdminClubs: "/admin/clubs",
  appAdminUsers: "/admin/users",
  appAdminGames: "/admin/games",
} as const;
